import type { SelectOption } from '@/constants/onboarding-options';
import i18n from '@/i18n';

const COUNTRY_DEFS = [
  { id: 'afghanistan', value: 'Afghanistan' },
  { id: 'albania', value: 'Albania' },
  { id: 'algeria', value: 'Algeria' },
  { id: 'angola', value: 'Angola' },
  { id: 'argentina', value: 'Argentina' },
  { id: 'australia', value: 'Australia' },
  { id: 'austria', value: 'Austria' },
  { id: 'bangladesh', value: 'Bangladesh' },
  { id: 'belgium', value: 'Belgium' },
  { id: 'benin', value: 'Benin' },
  { id: 'botswana', value: 'Botswana' },
  { id: 'brazil', value: 'Brazil' },
  { id: 'burkinaFaso', value: 'Burkina Faso' },
  { id: 'burundi', value: 'Burundi' },
  { id: 'capeVerde', value: 'Cabo Verde' },
  { id: 'cameroon', value: 'Cameroon' },
  { id: 'canada', value: 'Canada' },
  { id: 'centralAfricanRepublic', value: 'Central African Republic' },
  { id: 'chad', value: 'Chad' },
  { id: 'chile', value: 'Chile' },
  { id: 'china', value: 'China' },
  { id: 'colombia', value: 'Colombia' },
  { id: 'comoros', value: 'Comoros' },
  { id: 'congoDrc', value: 'Democratic Republic of the Congo' },
  { id: 'congoRepublic', value: 'Republic of the Congo' },
  { id: 'czechRepublic', value: 'Czech Republic' },
  { id: 'denmark', value: 'Denmark' },
  { id: 'djibouti', value: 'Djibouti' },
  { id: 'egypt', value: 'Egypt' },
  { id: 'equatorialGuinea', value: 'Equatorial Guinea' },
  { id: 'eritrea', value: 'Eritrea' },
  { id: 'eswatini', value: 'Eswatini' },
  { id: 'ethiopia', value: 'Ethiopia' },
  { id: 'finland', value: 'Finland' },
  { id: 'france', value: 'France' },
  { id: 'gabon', value: 'Gabon' },
  { id: 'gambia', value: 'Gambia' },
  { id: 'germany', value: 'Germany' },
  { id: 'ghana', value: 'Ghana' },
  { id: 'greece', value: 'Greece' },
  { id: 'guinea', value: 'Guinea' },
  { id: 'guineaBissau', value: 'Guinea-Bissau' },
  { id: 'hongKong', value: 'Hong Kong' },
  { id: 'hungary', value: 'Hungary' },
  { id: 'india', value: 'India' },
  { id: 'indonesia', value: 'Indonesia' },
  { id: 'iran', value: 'Iran' },
  { id: 'iraq', value: 'Iraq' },
  { id: 'ireland', value: 'Ireland' },
  { id: 'israel', value: 'Israel' },
  { id: 'italy', value: 'Italy' },
  { id: 'ivoryCoast', value: 'Ivory Coast' },
  { id: 'japan', value: 'Japan' },
  { id: 'jordan', value: 'Jordan' },
  { id: 'kenya', value: 'Kenya' },
  { id: 'lesotho', value: 'Lesotho' },
  { id: 'liberia', value: 'Liberia' },
  { id: 'libya', value: 'Libya' },
  { id: 'madagascar', value: 'Madagascar' },
  { id: 'malawi', value: 'Malawi' },
  { id: 'malaysia', value: 'Malaysia' },
  { id: 'mali', value: 'Mali' },
  { id: 'mauritania', value: 'Mauritania' },
  { id: 'mauritius', value: 'Mauritius' },
  { id: 'mexico', value: 'Mexico' },
  { id: 'morocco', value: 'Morocco' },
  { id: 'mozambique', value: 'Mozambique' },
  { id: 'namibia', value: 'Namibia' },
  { id: 'netherlands', value: 'Netherlands' },
  { id: 'newZealand', value: 'New Zealand' },
  { id: 'niger', value: 'Niger' },
  { id: 'nigeria', value: 'Nigeria' },
  { id: 'norway', value: 'Norway' },
  { id: 'pakistan', value: 'Pakistan' },
  { id: 'philippines', value: 'Philippines' },
  { id: 'poland', value: 'Poland' },
  { id: 'portugal', value: 'Portugal' },
  { id: 'romania', value: 'Romania' },
  { id: 'russia', value: 'Russia' },
  { id: 'rwanda', value: 'Rwanda' },
  { id: 'saoTomeAndPrincipe', value: 'São Tomé and Príncipe' },
  { id: 'saudiArabia', value: 'Saudi Arabia' },
  { id: 'senegal', value: 'Senegal' },
  { id: 'seychelles', value: 'Seychelles' },
  { id: 'sierraLeone', value: 'Sierra Leone' },
  { id: 'singapore', value: 'Singapore' },
  { id: 'somalia', value: 'Somalia' },
  { id: 'southAfrica', value: 'South Africa' },
  { id: 'southKorea', value: 'South Korea' },
  { id: 'southSudan', value: 'South Sudan' },
  { id: 'spain', value: 'Spain' },
  { id: 'sudan', value: 'Sudan' },
  { id: 'sweden', value: 'Sweden' },
  { id: 'switzerland', value: 'Switzerland' },
  { id: 'taiwan', value: 'Taiwan' },
  { id: 'tanzania', value: 'Tanzania' },
  { id: 'thailand', value: 'Thailand' },
  { id: 'togo', value: 'Togo' },
  { id: 'tunisia', value: 'Tunisia' },
  { id: 'turkey', value: 'Turkey' },
  { id: 'uganda', value: 'Uganda' },
  { id: 'ukraine', value: 'Ukraine' },
  { id: 'unitedArabEmirates', value: 'United Arab Emirates' },
  { id: 'unitedKingdom', value: 'United Kingdom' },
  { id: 'unitedStates', value: 'United States' },
  { id: 'vietnam', value: 'Vietnam' },
  { id: 'zambia', value: 'Zambia' },
  { id: 'zimbabwe', value: 'Zimbabwe' },
] as const;

/** Translated display options — call at render time, not at module scope. `value` is the literal English country name persisted to the DB — never translated. */
export function getCountryOptions(): SelectOption[] {
  return COUNTRY_DEFS.map(({ id, value }) => ({
    value,
    label: i18n.t(`shared.options.countries.${id}`),
  }));
}

export const PREDEFINED_COUNTRIES = COUNTRY_DEFS.map((c) => c.value);
